WORKFORCE_FACTS = [
    {
        "subject": "Delhivery",
        "predicate": "Team size",
        "value": "63713",
        "value_type": "number",
        "unit": "people",
        "period": "Q4 FY24",
        "scope": "permanent employees and contractual workers, excluding partner agents",
        "evidence_verified": True,
        "document_id": "03-delhivery-q4-fy24-earnings-presentation",
        "page_number": 8,
    },
    {
        "subject": "Delhivery",
        "predicate": "Partner agents",
        "value": "34422",
        "value_type": "number",
        "unit": "people",
        "period": "Q4 FY24",
        "scope": "last-mile delivery partner agents in the last month",
        "evidence_verified": True,
        "document_id": "03-delhivery-q4-fy24-earnings-presentation",
        "page_number": 8,
    },
    {
        "subject": "Delhivery",
        "predicate": "Workforce strength",
        "value": "98135",
        "value_type": "number",
        "unit": "people",
        "period": "FY24",
        "scope": "permanent employees, contractual workers and last-mile delivery partner agents",
        "evidence_verified": True,
        "document_id": "02-delhivery-annual-report-fy24-excerpt",
        "page_number": 2,
    },
]