ANNUAL_REPORT_FACTS = [
    {
        "subject": "Delhivery",
        "predicate": "Revenue from services",
        "value": "81415",
        "value_type": "number",
        "unit": "₹ million",
        "period": "FY24",
        "scope": None,
        "evidence_verified": True,
        "document_id": "02-delhivery-annual-report-fy24-excerpt",
        "page_number": 6,
    },
    {
        "subject": "Delhivery",
        "predicate": "Revenue from services",
        "value": "72236",
        "value_type": "number",
        "unit": "₹ million",
        "period": "FY23",
        "scope": None,
        "evidence_verified": True,
        "document_id": "02-delhivery-annual-report-fy24-excerpt",
        "page_number": 6,
    },
    {
        "subject": "Delhivery",
        "predicate": "Express parcel shipment volume",
        "value": "740",
        "value_type": "number",
        "unit": "million",
        "period": "FY24",
        "scope": None,
        "evidence_verified": True,
        "document_id": "02-delhivery-annual-report-fy24-excerpt",
        "page_number": 6,
    },
]


PRESENTATION_FACTS = [
    {
        "subject": "Delhivery",
        "predicate": "Revenue from services",
        "value": "8142",
        "value_type": "number",
        "unit": "₹ Cr",
        "period": "FY24",
        "scope": None,
        "evidence_verified": True,
        "document_id": "03-delhivery-q4-fy24-earnings-presentation",
        "page_number": 9,
    },
    {
        "subject": "Delhivery",
        "predicate": "Revenue from services",
        "value": "7224",
        "value_type": "number",
        "unit": "₹ Cr",
        "period": "FY23",
        "scope": None,
        "evidence_verified": True,
        "document_id": "03-delhivery-q4-fy24-earnings-presentation",
        "page_number": 9,
    },
    {
        "subject": "Delhivery",
        "predicate": "Express Parcel shipments",
        "value": "740",
        "value_type": "number",
        "unit": "Mn",
        "period": "FY24",
        "scope": None,
        "evidence_verified": True,
        "document_id": "03-delhivery-q4-fy24-earnings-presentation",
        "page_number": 9,
    },
    {
        "subject": "Delhivery",
        "predicate": "Express Parcel revenue",
        "value": "5077",
        "value_type": "number",
        "unit": "₹ Cr",
        "period": "FY24",
        "scope": None,
        "evidence_verified": True,
        "document_id": "03-delhivery-q4-fy24-earnings-presentation",
        "page_number": 9,
    },
    {
        "subject": "Delhivery",
        "predicate": "PTL freight revenue",
        "value": "1429",
        "value_type": "number",
        "unit": "₹ Cr",
        "period": "FY24",
        "scope": None,
        "evidence_verified": True,
        "document_id": "03-delhivery-q4-fy24-earnings-presentation",
        "page_number": 9,
    },
]